version: '3'
services:
  nginx:
    restart: always
    image: nginx:dev
    container_name: nginx-dev
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 4000:80
    depends_on:
      - strapi
      - frontend

  strapi:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    image: strapi:dev
    container_name: strapi-dev
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 1337:1337

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    image: frontend:dev
    container_name: frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000