version: '3'
services:
  frontend:
    image: public.ecr.aws/v7f1v7z3/tax-dd-ecr-frontend:latest
    container_name: frontend-test
    ports:
      - 3000:3000

  nginx:
    image: public.ecr.aws/v7f1v7z3/tax-dd-ecr-nginx:latest
    restart: always
    container_name: nginx-test
    ports:
      - 4000:80
    depends_on:
      - strapi
      - frontend

  strapi:
    image: public.ecr.aws/v7f1v7z3/tax-dd-ecr-strapi:latest
    container_name: strapi-test
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      NODE_ENV: PRODUCTION
    ports:
      - 1337:1337