version: '3'
services:
  strapi:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: strapi
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
        NODE_ENV: PRODUCTION
    ports:
      - 1337:1337
      
  frontend:
    build:
      dockerfile: .
      context: ./frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000