version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    build:
      dockerfile: .
      context: ./nginx
    ports:
      - 4000:80
    depends_on:
      - strapi
      - frontend

  strapi:
    build:
      dockerfile: .
      context: ./backend
    image: strapi:latest
    container_name: strapi
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
        NODE_ENV: PRODUCTION
    ports:
      - 1337:1337
      
  # frontend:
  #   build:
  #     dockerfile: .
  #     context: ./frontend
  #   image: frontend:latest
  #   restart: always
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #     - /app/.next
  #   ports:
  #     - 3000:3000

  frontend:
    image: frontend:latest
    container_name: app-prod
    build:
      dockerfile: .
      context: ./frontend1
    ports:
      - 3000:3000