version: '3'
services:
  strapi:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: strapi_dockerize
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
        NODE_ENV: PRODUCTION
    ports:
      - 1337:1337