version: '3'
services:
  strapi:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 1337:1337
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000