FROM nginx:1.20.2-alpine
COPY ./default.conf /etc/nginx/conf.d/default.conf
# COPY ./upstream.conf /etc/nginx/conf.d/upstream.conf
# COPY ./strapi.conf /etc/nginx/sites-available/strapi.conf

# RUN ln -s /etc/nginx/sites-available/strapi.conf /etc/nginx/sites-enabled/